name: Weapons
main: me.zabzabdoda.Weapons.Weapons
version: 1.0
api-version: 1.14
author: zabzabdoda
description: Adds weapons for TTT plugin
commands:
  weapon:
    description: Main command for Weapons.
    usage: |
           /weapon <give|list|help>
           Example: /weapon give m16 - Gives you an m16 weapon.
