name: Weapons
main: me.zabzabdoda.Weapons.Weapons
version: 1.0
api-version: 1.14
author: zabzabdoda
description: Loot Locations plugin
commands:
  weapon:
    description: Main command for BananaUHC.
    usage: |
           /weapon <give|list|help>
           Example: /weapon wand - Give you the wand to generate loot.